### ISSUE TITLE
Decide how to calculate errors

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpobench#4]
One idea is to have another key in the YAML that specifies which error measure gets calculated:

```
error_function:
  - ibug_68_48_points_face_size
```

But this may be overly complicated. Perhaps the number of landmarks expected should be handled by another key? Or perhaps normalisation should be separate?

The biggest problem is something like Intraface which only returns 49 points - what if we trained on 68?

**Comment by jabooth** [comment]
Implemented as landmark processes.
