### ISSUE TITLE
Finding Matlab

### ISSUE THREAD

**Issue by patricksnape** [menpo/menpobench#5]
At the moment, we plan on natively supporting Matlab in a thorough manner. Therefore, we need to be able to reliably call out to Matlab. We could just say that users have to sort this themselves, but that is very unfriendly on OSX and Windows where matlab is not on the path by default. We should probably have some sort of logic that tries to work out which Matlab is installed, and if it fails it should fallback to something like the caching mechanism and store it in the `.menpobench` config file.

We should probably add Matlab existence to YAML validation as well.

**Comment by jabooth** [comment]
Addressed with #8
